---
# DotGit Sync Configuration
# ------------------------------------------------------------------------------
version: v1alpha1
dotgit:
  source:
    git:
      url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
      ref: main
  yaml: &merge_enforce
    merge:
      method: only
      only:
        - .pre-commit-config.yaml
        - gitlab-ci.yaml
    enforce:
      method: only
      only:
        - .pre-commit-config.yaml
        - gitlab-ci.yaml
  json:
    <<: *merge_enforce

# Repos description and template usage configuration
# ------------------------------------------------------------------------------
name: OpenTofu Module Cloudflare DNS
slug: cloudflare-dns
description: |-
  OpenTofu modules allowing to manage cloudflare dns configuration.
licenses:
  date:
    first_year: "2024"
  copyright:
    Romain Deville: code@romaindeville.fr
  primary: MIT
  secondaries:
    - BEERWARE
maintainers:
  Romain Deville: code@romaindeville.fr
gitignore:
  templates:
    - base
  query:
    - terraform
templates:
  - base
  - base-ci-gitlab
  - base-pre-commit
  - commitlint-pre-commit
  - markdown
  - markdown-pre-commit
  - markdown-ci-gitlab
  - opentofu
  - opentofu-pre-commit
  - opentofu-ci-gitlab

# Everything below is only used as variables in templates
# ------------------------------------------------------------------------------
extra:
  code_of_conduct:
    abuse: abuse+code@romaindeville.fr
  maintainers:
    Romain Deville:
      socials:
        Website:
          alt: &website https://romaindeville.fr
          url: *website
        Cloudflare:
          alt: "@rdeville"
          url: https://cloudflare.com/rdeville
        Gitlab:
          alt: "@r.deville"
          url: https://gitlab.com/r.deville
        Framagit:
          alt: "@rdeville"
          url: https://framagit.org/rdeville
  repo:
    url: https://framagit.org/rdeville-public/opentofu/cloudflare-groups
